# NumPy Illustrated: The Visual Guide to NumPy

### Pourquoi Numpy au lieu des Listes en python?
L'exemple le plus simple lorsque les tableaux NumPy battent des listes est arithmétique :
- plus compact, surtout lorsqu'il y a plus d'une dimension
- plus rapide que les listes lorsque l'opération peut être vectorisée
- plus lent que les listes lorsque vous ajoutez des éléments à la fin
- habituellement homogène : ne peut travailler rapidement qu'avec des éléments d'un seul type

Quelques significations:
- O(N)  --> see Big-O Cheat Sheet And (proportional to the size of the array)
- O*(1) --> the so-called “amortized” O(1) (le temps d'execution ne dépend généralement pas de la taille du tableau)

## 1-Numpy Array vs. Python List

### 1_1-With python List

In [1]:
# Mutiplication d'une liste python par 2 
a = [1, 2, 3]
print("Avec la list en python")
[q*2 for q in a]

Avec la list en python


[2, 4, 6]

In [2]:
# Somme de 2 tableaux avec les list Python
a = [1, 2, 3]
b = [4, 5, 6]
[q+r for q,r in zip(a, b)]

[5, 7, 9]

### 1_2-With Numpy library

In [3]:
# Mutiplication d'un tableau (numpy) par 2 
import numpy as np
a = np.array([1, 2, 3])
print("Avec la Biblio Numpy")
a*2

Avec la Biblio Numpy


array([2, 4, 6])

In [4]:
# Somme de 2 tableaux avec Numpy
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

## 2. Vectors, the 1D Arrays

## 2_1-Vector initialization

In [5]:
a = np.array([1., 2., 3.])

In [6]:
#Afficher le type du tableau
a.dtype

dtype('float64')

In [7]:
#Afficher la dimension du tableau
a.shape

(3,)

In [8]:
# préallouer l'espace nécessaire pour un tableau
b = np.zeros(3, int)
print("L'array suivant est de type : ", b.dtype)
b

L'array suivant est de type :  int32


array([0, 0, 0])

Il est souvent nécessaire de créer un tableau vide qui correspond à celui existant par forme et type d'éléments

In [9]:
c = np.zeros_like(a)
print("L'array suivant crée en fonction de a est de type:", c.dtype )
print("Et de taille-->", c.shape)
c

L'array suivant crée en fonction de a est de type: float64
Et de taille--> (3,)


array([0., 0., 0.])

#### En fait, toutes les fonctions qui créent un tableau rempli d'une valeur constante ont une contrepartie _like

In [10]:
print("np.zeros(3) --> ",np.zeros(3))
print("np.ones(3) --> ", np.ones(3))
print("np.empty(3) --> ", np.empty(3))
print("np.full(3, 7.) --> ", np.full(3, 7.))

a = np.array([1, 2, 3])
print("np.zeros_like(a) --> ", np.zeros_like(a))
print("np.ones_like(a) --> ", np.ones_like(a))
print("np.empty_like(a) --> ", np.empty_like(a))
print("np.full_like(a, 7) --> ", np.full_like(a, 7))

np.zeros(3) -->  [0. 0. 0.]
np.ones(3) -->  [1. 1. 1.]
np.empty(3) -->  [1. 1. 1.]
np.full(3, 7.) -->  [7. 7. 7.]
np.zeros_like(a) -->  [0 0 0]
np.ones_like(a) -->  [1 1 1]
np.empty_like(a) -->  [1 1 1]
np.full_like(a, 7) -->  [7 7 7]


#### Remarque (Question): En 1ère execution de np.empty(a), ce dernier ne contiendra pas directement les valeurs  a après une exection de a qui date d'une certaine durée, à moins qu'on l'execute un nbre de fois >= 2

#### Il y a jusqu'à deux fonctions pour l'initialisation du tableau avec une séquence monotone dans NumPy

In [11]:
print("np.arange(6) --> ", np.arange(6))
print("np.arange(2, 6) --> ", np.arange(2, 6))
print("np.arange(1, 6, 2) --> ", np.arange(1, 6, 2))
#n'est pas particulièrement bon pour manipuler les floats, on utilise généralement linspace()
print("np.linspace(0, 0.5, 6) --> ", np.linspace(0, 0.5, 6))
# np.linspace(start, stop, numbre d'item)

np.arange(6) -->  [0 1 2 3 4 5]
np.arange(2, 6) -->  [2 3 4 5]
np.arange(1, 6, 2) -->  [1 3 5]
np.linspace(0, 0.5, 6) -->  [0.  0.1 0.2 0.3 0.4 0.5]


In [12]:
# np.arange(start, stop, numbre d'item)
print("np.arange(0.4, 0.8, 0.1) --> ", np.arange(0.4, 0.8, 0.1))

np.arange(0.4, 0.8, 0.1) -->  [0.4 0.5 0.6 0.7]


In [13]:
# Le methodes du module random
import random
print("np.random.randint(0, 10, 3) --> ", np.random.randint(0, 10, 3))
print("np.random.rand(3) --> ", np.random.rand(3))
print("np.random.uniform(1, 10, 3) --> ", np.random.uniform(0, 10, 3))
print("np.random.randn(3) --> ", np.random.randn(0, 10, 3))
print("np.random.normal(5, 2, 3) --> ", np.random.normal(5, 2, 3))

np.random.randint(0, 10, 3) -->  [4 6 7]
np.random.rand(3) -->  [0.50452964 0.50667778 0.78229862]
np.random.uniform(1, 10, 3) -->  [6.54112197 2.7553462  0.64325883]
np.random.randn(3) -->  []
np.random.normal(5, 2, 3) -->  [7.49139439 5.36471875 3.36577621]


#### Une nouvelle interface pour la génération de tableaux aléatoires

In [14]:
rng = np.random.default_rng()

print("rng.integers(0, 10, 3) --> ", rng.integers(0, 10, 3))
print("rng.integers(0, 10, 3, endpoint = True) --> ", rng.integers(0, 10, 3, endpoint = True))
print("rng.random(3) --> ", rng.integers(3))
print("rng.uniform(1, 10, 3) --> ", rng.uniform(1, 10, 3))
print("rng.standard_normal(3) --> ", rng.standard_normal(3))
print("rng.normal(5, 2, 3) --> ", rng.uniform(1, 10, 3))


rng.integers(0, 10, 3) -->  [1 0 4]
rng.integers(0, 10, 3, endpoint = True) -->  [10  1  8]
rng.random(3) -->  0
rng.uniform(1, 10, 3) -->  [3.82289951 6.69395828 6.57405922]
rng.standard_normal(3) -->  [ 1.19454891  0.80467299 -0.25252261]
rng.normal(5, 2, 3) -->  [5.58351811 9.79743696 6.42633223]


## 2_2- Vector indexing

In [15]:
a = np.arange(1, 6)
print("a[1] -->", a[1])
print("a[2:4] -->", a[2:4])
print("a[-2:] -->", a[-2:])
print("a[::2] -->", a[::2])
print("a[[1, 3, 4]] -->", a[[1, 3, 4]], "(indexation sophistiquée)")

a[1] --> 2
a[2:4] --> [3 4]
a[-2:] --> [4 5]
a[::2] --> [1 3 5]
a[[1, 3, 4]] --> [2 4 5] (indexation sophistiquée)


### Copie avec les listes python

In [16]:
a = [1, 2, 3]
b = a
c = a[:]
d = a.copy()

In [17]:
print("b -->", b)
print("c -->", c)
print("d -->", d)

b --> [1, 2, 3]
c --> [1, 2, 3]
d --> [1, 2, 3]


* Effacer une liste

In [18]:
del a

In [19]:
print("b -->", b)
print("c -->", c)
print("d -->", d)

b --> [1, 2, 3]
c --> [1, 2, 3]
d --> [1, 2, 3]


### Copie avec le librairie numpy

In [34]:
a = np.array([1, 2, 3])
b = a
c = a[:]
d = a.copy()

In [35]:
print("b -->", b)
print("c -->", c)
print("d -->", d)

b --> [1 2 3]
c --> [1 2 3]
d --> [1 2 3]


#### Le code suivant marche pas avec les listes en python mais ne marche pas avec numpy

In [36]:
# Avec List()
a = [1, 2, 3]
a[1:2] = [4, 5] #Inserer 4 et 5 a l'indice 1 de a
a

[1, 4, 5, 3]

In [37]:
# Essayons avec array
a = np.array([1, 2, 3])
a[1:2] = [4, 5] #Inserer 4 et 5 a l'indice 1 de a
a

ValueError: could not broadcast input array from shape (2,) into shape (1,)

Apres execution on se rend tout de suite compte que ça ne marche pas avec l'array de numpy, donc pour se faire, on pourra utiliser la methode .insert et .append

### Une autre manière d'acceder à un tableau array est l'indexation booleene

In [38]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
print("np.any(a>5) --> ", np.any(a>5))
print("np.all(a>5) --> ", np.all(a>5))
print("a[a>5] --> ", a[a>5]) # Retourne les valeurs en question elle même

np.any(a>5) -->  True
np.all(a>5) -->  False
a[a>5] -->  [6 7 6]


In [39]:
a[a>5] = 0 # Remplace les valeurs de a superieures à 5 par 0
a

array([1, 2, 3, 4, 5, 0, 0, 0, 5, 4, 3, 2, 1])

In [40]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
a[(a>=3) & (a<=5)] = 0
# Mais attention la comparaison ternaire comme 3<a<=8 ne marche pas ici
a

array([1, 2, 0, 0, 0, 6, 7, 6, 0, 0, 0, 2, 1])

 ### Utilisation des methodes n.where et .np.clip

In [41]:
a = np.array([1, 2, 3, 4, 5, 0, 0, 0, 6, 7, 6, 5, 4, 3, 2, 1])
print("np.where(a>5) -->", np.where(a>5))
print("np.nonzero(a>5) -->", np.nonzero(a>5))
# Ces 2 methodes retournent les indices
# Mais quelle différence entre les deux ????

np.where(a>5) --> (array([ 8,  9, 10], dtype=int64),)
np.nonzero(a>5) --> (array([ 8,  9, 10], dtype=int64),)


#### np.where()

In [42]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
a[a<5] = 0
a[a>=5] = 1
print(a)

[0 0 0 0 1 1 1 1 1 0 0 0 0]


In [43]:
# ce code est le même que celui au dessus
a = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
print("np.where(a>=5, 1, 0) -->", np.where(a>=5, 1, 0))

np.where(a>=5, 1, 0) --> [0 0 0 0 1 1 1 1 1 0 0 0 0]


np.where retourne un tuple

#### NB: np.where(condition, valeur_à_affectée_pour_ceux_qui_vérifie_la_condition, valeur_à_affectée_pour_ceux_qui_ne_vérifie_pas_la_condition)

#### np.clip()

In [44]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
a[a<2] = 2
a[a>5] = 5
print(a)

[2 2 3 4 5 5 5 5 5 4 3 2 2]


In [45]:
# ce code est le même que celui au dessus
a = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
print("np.clip(a, 2, 5)-->", np.clip(a, 2, 5))

np.clip(a, 2, 5)--> [2 2 3 4 5 5 5 5 5 4 3 2 2]


#### NB: np.clip(a, min, max)

### Vector Operations

#### La plupart des fonctions mathématiques ont des homologues NumPy qui peuvent gérer des vecteurs

In [46]:
a = np.array([1, 2])
a1 = np.array([1, 2, 3])
b = np.array([9, 4])
c = np.array([np.pi, np.pi/2])
d1 = np.array([0, 1])
d2 = np.array([1, 0])
e = [2.3, 2.5, 2.7]

print("b**2 ---> ", b**2)
print("np.sqrt(b) ---> ", np.sqrt(b))
print("np.exp(b) ---> ", np.exp(b))
print("np.log(np.array([np.e, np.e**2])) ---> ", np.log(np.array([np.e, np.e**2])) )
print("a produit scalaire b --->", np.dot(a, b))
print("a X b --->", np.cross(a, b))
print("np.sin(c) --->", np.sin(c))
result = np.sin(c)
print("np.arcsin(result) -->", np.arcsin(result))
print("np.arctan2(d1, d2) -->", np.arctan2(d1, d2))
print("np.floor(np.array[2.3, 2.5, 2.7]) -->", np.floor(e))
print("np.ceil(np.array[2.3, 2.5, 2.7]) -->", np.ceil(e))
print("np.round(np.array[2.3, 2.5, 2.7]) -->", np.round(e))
print("np.max(a1) -->", np.max(a1))
print("a1.max() -->", a1.max())
print("np.min(a1) -->", np.min(a1))
print("a1.sum() -->", a1.sum())
print("a1.var() -->", a1.var())
print("a1.argmax() -->", a1.argmax())
print("a1.argmin() -->", a1.argmin())
print("a1.mean() -->", a1.mean())
print("a1.std() -->", a1.std())

b**2 --->  [81 16]
np.sqrt(b) --->  [3. 2.]
np.exp(b) --->  [8103.08392758   54.59815003]
np.log(np.array([np.e, np.e**2])) --->  [1. 2.]
a produit scalaire b ---> 17
a X b ---> -14
np.sin(c) ---> [1.2246468e-16 1.0000000e+00]
np.arcsin(result) --> [1.22464680e-16 1.57079633e+00]
np.arctan2(d1, d2) --> [0.         1.57079633]
np.floor(np.array[2.3, 2.5, 2.7]) --> [2. 2. 2.]
np.ceil(np.array[2.3, 2.5, 2.7]) --> [3. 3. 3.]
np.round(np.array[2.3, 2.5, 2.7]) --> [2. 2. 3.]
np.max(a1) --> 3
a1.max() --> 3
np.min(a1) --> 1
a1.sum() --> 6
a1.var() --> 0.6666666666666666
a1.argmax() --> 2
a1.argmin() --> 0
a1.mean() --> 2.0
a1.std() --> 0.816496580927726


#### La standard deviation (ou ecart-type) juste au dessus ignore donne un résultat biaisé dans le cas d'utilisation où la moyenne de la population est inconnue. L'approche standard pour obtenir une estimation moins biaisée est d'avoir n-1 dans le dénominateur, ce qui est fait avec ddof=1 ("delta degrés de liberté") :

In [47]:
a1.std(ddof = 1)

1.0

L'effet de la correction de Bessel diminue rapidement avec l'augmentation de la taille de l'échantillon. De plus, il ne s'agit pas d'une solution unique, par ex. pour la distribution normale ddof=1.5 est mieux

In [48]:
# difference entre std(simple), std avec ddof = 1 et ddof = 1.5
res, res1, res2 = [], [], []
import random

for i in range(10000):
    a = np.random.randn()
    print("a = ", a)
    print("res.append(a.std())", res.append(a.std())) #ça ne marche pas
    print("res1.append(a.std())", res1.append(a.std(ddof =1)))
    print("res2.append(a.std())", res2.append(a.std(ddof = 1.5)))

a =  -1.7940641423183281


AttributeError: 'float' object has no attribute 'std'

#### Quelques fonctions de trie

Elles ont moins de capacités que leurs homologues python

- Liste python

In [49]:
a = [1, 2, 3, 6, 10]
print("a.sort()", a.sort())
print("sorted(a)",sorted(a))
print("a.sort(key=f)", a.sort(key=f)) #Pourquoi la clé f ne marche pas?
print("a.sort(reversed=False)", a.sort(reversed=False))

a.sort() None
sorted(a) [1, 2, 3, 6, 10]


NameError: name 'f' is not defined

- array de numpy

In [50]:
a = np.array([1, 2, 3, 6, 10])
print("a.sort()", a.sort())
print("np.sort(a)",np.sort(a))

a.sort() None
np.sort(a) [ 1  2  3  6 10]


### Recherche d'element dans un vecteur

Avec Numpy pas de methode index comme avec les listes

In [51]:
a = [1, 2, 3, 4, 67]
a.index(2[ i[ j]]) #La 1ère occurence de x entre l'indice x et y
#ça ne marche pas

<>:2: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:2: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
C:\Users\Oussou\AppData\Local\Temp\ipykernel_7356\161692067.py:2: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  a.index(2[ i[ j]]) #La 1ère occurence de x entre l'indice x et y
C:\Users\Oussou\AppData\Local\Temp\ipykernel_7356\161692067.py:2: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  a.index(2[ i[ j]]) #La 1ère occurence de x entre l'indice x et y
C:\Users\Oussou\AppData\Local\Temp\ipykernel_7356\161692067.py:2: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  a.index(2[ i[ j]]) #La 1ère occurence de x entre l'indice x et y


NameError: name 'j' is not defined

In [52]:
a = np.array([1, 2, 3, 6, 10])
np.where(a==0)[0][0]
next(i[0] for i, v in np.ndenumerate(a) if v==x)
np.searchsorted(a, x)
#ça ne marche pas non plus

IndexError: index 0 is out of bounds for axis 0 with size 0

#### Comparaison des réels

In [53]:
import math
print("0.1 + 0.2 == 0.3 -->", 0.1 + 0.2 == 0.3)
print("np.allclose -->", np.allclose(0.1 + 0.2, 0.3))
print("math.isclose -->", math.isclose(0.1 + 0.2, 0.3))

0.1 + 0.2 == 0.3 --> False
np.allclose --> True
math.isclose --> True


##### NB: Un problème mineur dans np.allclose : np.allclose(a, b) != np.allclose(b, a)
Ce problème fut resolu avec la venu de np.isclose()
- Remarque: Je n'ai toujours pas pigé la difference entre ces 2

## 3-Les Matrices 2D

#### 3_1-Leur initialisation est simulaire à celle des vecteurs

In [ ]:
print("a = [[1, 2, 3], [4, 5, 6]] --> ",[[1, 2, 3], [4, 5, 6]])
print("- np.zeros((3, 2)) \n", np.zeros((3, 2)))
print("- np.full((3, 2), 7) \n", np.full((3, 2), 7))
print("- np.ones((3, 2)) \n", np.ones((3, 2)))
print("- np.empty((3, 2)) \n", np.empty((3, 2)))
print("- np.eye((3, 3)) \n", np.eye(3, 3)) # np.eye((3, 3)) = np.eye(3)


#### 3_2-Génération de matrices aléatoires

In [24]:
print("- randint\n", np.random.randint(0, 10, (3, 2)), "\n")
print("- rand\n", np.random.rand(3, 2), "\n")
print("- Uniform\n", np.random.uniform(1, 10, (3, 2)), "\n")
print("- normal\n", np.random.normal(10, 2, (3, 2)), "\n")
print("- normal\n", np.random.normal(10, 2, (3, 2)), "\n")
print("- randn\n", np.random.randn(3, 2), "\n")

- randint
 [[6 0]
 [8 8]
 [7 3]] 

- rand
 [[0.28605651 0.9666053 ]
 [0.94768163 0.58453476]
 [0.0885823  0.28079916]] 

- Uniform
 [[7.52539997 3.82751233]
 [9.7059113  6.32767259]
 [2.90038327 4.37678983]] 

- normal
 [[10.75973766 10.49249071]
 [12.06039762 10.69401613]
 [10.72753609  8.41823291]] 

- normal
 [[15.0480693   9.84757007]
 [10.62654122 10.78907531]
 [ 5.40192337  9.01965982]] 

- randn
 [[-0.04005215 -0.97042269]
 [ 0.55060281  2.25214307]
 [-1.69633278 -1.85248193]] 



In [25]:
rng = np.random.default_rng()
print("integers --> ", rng.integers(0, 10, 3))
print("random -->", rng.random(3))
print("standard_normal -->", rng.standard_normal(3))

integers -->  [9 5 1]
random --> [0.30273073 0.12902459 0.03428689]
standard_normal --> [ 0.8861127  -0.46362586 -0.04700492]


##### L'indexage en 2D est plus pratique qu'en les liste imbriquées

In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("- a\n", a, "\n")
print("- a[1,:]\n", a[1,:], "\n")
print("- a[:,2]\n", a[:,2], "\n")
print("- a[:,2:3]\n", a[:,2:3], "\n")
print("- a[-2:,-2:]\n", a[-2:,-2:], "\n")
print("- a[::2:,1::2]\n", a[::2,1::2], "\n") # a[start:end:step]

- a
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

- a[1,:]
 [5 6 7 8] 

- a[:,2]
 [ 3  7 11] 

- a[:,2:3]
 [[ 3]
 [ 7]
 [11]] 

- a[-2:,-2:]
 [[ 7  8]
 [11 12]] 

- a[::2:,1::2]
 [[ 2  4]
 [10 12]] 



#### The axis argument

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a.sum() -->", a.sum())
print("a.sum(axis = 0) -->", a.sum(axis = 0)) # Pour les lignes
print("a.sum(axis = 1) -->", a.sum(axis = 1)) # Pour les colonnes


a.sum() --> 21
a.sum(axis = 0) --> [5 7 9]
a.sum(axis = 1) --> [ 6 15]


In [28]:
# EinsSum
print("Einstein Sommation -->\nnp.einsum('ij->i', a)\n", np.einsum('ij->i', a))

Einstein Sommation -->
np.einsum('ij->i', a)
 [ 6 15]


#### Arithmetique des matrices

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("- a+b -->\n", a+b, "\n")
print("- a-b -->\n", a-b, "\n")
print("- a*b -->\n", a*b, "\n")
print("- a@b -->\n", a@b, "\n")
print("- a*b -->\n", a**b, "\n")
print("- a/b -->\n", a/b, "\n")

- a+b -->
 [[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]] 

- a-b -->
 [[0 2 3]
 [4 4 6]
 [7 8 8]] 

- a*b -->
 [[1 0 0]
 [0 5 0]
 [0 0 9]] 

- a@b -->
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

- a*b -->
 [[1 1 1]
 [1 5 1]
 [1 1 9]] 

- a/b -->
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]] 



C:\Users\Oussou\AppData\Local\Temp\ipykernel_6268\3829367878.py:8: RuntimeWarning: divide by zero encountered in true_divide
  print("- a/b -->\n", a/b, "\n")


In [30]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([[1, 2, 3, 4, 5, 6]])
print("- a.T\n", a.T, "\n")
print("- a.reshape(-1, 2)\n", a.reshape(-1, 2), "\n")
print("- b.T\n", b.reshape(3, 2), "\n")
print("- b[None, :]\n", b[None, :], "\n")


- a.T
 [[1 5]
 [2 6]
 [3 7]
 [4 8]] 

- a.reshape(-1, 2)
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

- b.T
 [[1 2]
 [3 4]
 [5 6]] 

- b[None, :]
 [[[1 2 3 4 5 6]]] 



In [31]:
print("b.flatten()\n", b.flatten())
print("b.reshape(-1)\n", b.reshape(-1))
print("(b.T).squeeze()\n", (b.T).squeeze())
print("np.ravel(b)\n", np.ravel(b))

b.flatten()
 [1 2 3 4 5 6]
b.reshape(-1)
 [1 2 3 4 5 6]
(b.T).squeeze()
 [1 2 3 4 5 6]
np.ravel(b)
 [1 2 3 4 5 6]


#### join arrays

In [32]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = b.reshape(-1, 2)
c = np.array([[1, 2, 3, 4, 5, 6, 7, 8]])

print("-hstack: \n", np.hstack((a, b)))
print("\n-vstack: \n", np.vstack((a,c.reshape(2, -1))))

-hstack: 
 [[ 1  2  3  4  1  2]
 [ 5  6  7  8  3  4]
 [ 9 10 11 12  5  6]]

-vstack: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [33]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([1, 2, 3, 4])
c = np.array([1, 3, 5])
c = c.T
jointure_hor =np.hstack((a, c[:, None]))
jointure_ver = np.vstack((a, b))
print("- hstack(a, c)\n", jointure_hor) # <=> np.column_stack((a, c))
print("\n- vstack(a, b)\n", jointure_ver)

- hstack(a, c)
 [[ 1  2  3  4  1]
 [ 5  6  7  8  3]
 [ 9 10 11 12  5]]

- vstack(a, b)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


#### Le contraire de (hstack et vstack) la jointure est --> hsplit() et vsplit()
- si hstack() est la fonction alors nous pôuvons considerer hsplit() comme sa bijection
- De meme pour vstack() et vsplit()

In [34]:
a, c = np.hsplit(jointure_hor, [4])
a, b = np.vsplit(jointure_ver, [3])
print("- hsplit()")
print("a:\n", a)
print("c:\n", c)
print("\n- vsplit()")
print("a:\n", a)
print("b:\n", b)


- hsplit()
a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
c:
 [[1]
 [3]
 [5]]

- vsplit()
a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b:
 [[1 2 3 4]]


In [35]:
h = np.random.randint(1, 13, (3,6))
print("h:\n", h)
a, c = np.hsplit(h, [4])
print("\n-np.hsplit(h, [4])")
print("a:\n", a)
print("c:\n", c)


h:
 [[ 9  4  4 11  5  2]
 [ 8  8  4 10  1  1]
 [ 6  8  2  9 12  7]]

-np.hsplit(h, [4])
a:
 [[ 9  4  4 11]
 [ 8  8  4 10]
 [ 6  8  2  9]]
c:
 [[ 5  2]
 [ 1  1]
 [12  7]]


In [36]:
print("h:\n", h)
a, b, c = np.hsplit(h, [3, 4])
print("\n-np.hsplit(h, [3, 4])")
print("a:\n", a)
print("b:\n", b)
print("c:\n", c)

h:
 [[ 9  4  4 11  5  2]
 [ 8  8  4 10  1  1]
 [ 6  8  2  9 12  7]]

-np.hsplit(h, [3, 4])
a:
 [[9 4 4]
 [8 8 4]
 [6 8 2]]
b:
 [[11]
 [10]
 [ 9]]
c:
 [[ 5  2]
 [ 1  1]
 [12  7]]


In [37]:
print("h:\n", h)
a, b, c = np.hsplit(h, 3)
print("\n-np.hsplit(h, 3)")
print("a:\n", a)
print("b:\n", b)
print("c:\n", c)

h:
 [[ 9  4  4 11  5  2]
 [ 8  8  4 10  1  1]
 [ 6  8  2  9 12  7]]

-np.hsplit(h, 3)
a:
 [[9 4]
 [8 8]
 [6 8]]
b:
 [[ 4 11]
 [ 4 10]
 [ 2  9]]
c:
 [[ 5  2]
 [ 1  1]
 [12  7]]


#### - Duplication de matrice

In [38]:
a = np.array([[1, 2,],[ 3, 4]])
print("- np.tile\n", np.tile(a, (2, 3)))

- np.tile
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [39]:
a = np.array([[1, 2,],[ 3, 4]])
b = a.repeat(3, axis=1)
print("- b = a.repeat(3,axis=1)\n", b)
print("\n- b.repeat(2, axis=0)\n", b.repeat(2, axis=0))


- b = a.repeat(3,axis=1)
 [[1 1 1 2 2 2]
 [3 3 3 4 4 4]]

- b.repeat(2, axis=0)
 [[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]]


- delete

In [40]:
a = np.arange(1, 16)
a = a.reshape(3, 5)
print("a:\n", a)

print("\n- np.delete(a, [1, 3], axis=1)\n", np.delete(a, [1, 3], axis=1))
print("\n- np.delete(a, 1, axis=0)\n", np.delete(a, 1, axis=0))
print("\n- np.delete(a, np.s_[1:-1], axis=1)\n", np.delete(a, np.s_[1:-1], axis=1))
print("\n- np.delete(a, slice(1, -1), axis=1)\n", np.delete(a, slice(1, -1), axis=1))


a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

- np.delete(a, [1, 3], axis=1)
 [[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]

- np.delete(a, 1, axis=0)
 [[ 1  2  3  4  5]
 [11 12 13 14 15]]

- np.delete(a, np.s_[1:-1], axis=1)
 [[ 1  5]
 [ 6 10]
 [11 15]]

- np.delete(a, slice(1, -1), axis=1)
 [[ 1  5]
 [ 6 10]
 [11 15]]


- Insert

In [41]:
h = np.arange(1, 18, 2)
h = h.reshape(3, 3)

print("h:\n", h)
print("\n- np.insert(h, [1, 2], 0, axis=1)\n", np.insert(h, [1, 2], 0, axis=1))

h:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]

- np.insert(h, [1, 2], 0, axis=1)
 [[ 1  0  3  0  5]
 [ 7  0  9  0 11]
 [13  0 15  0 17]]


In [42]:
v = np.arange(1, 11)
v = v.reshape(2, 5)
print("v:\n", v)
print("\n- np.insert(v, 1, 7, axis=0)\n", np.insert(v, 1, 7, axis=0))


v:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

- np.insert(v, 1, 7, axis=0)
 [[ 1  2  3  4  5]
 [ 7  7  7  7  7]
 [ 6  7  8  9 10]]


In [43]:
u = np.random.randint(1, 16, (3, 2))
w = np.random.randint(1, 16, (3, 3))
print("u:\n", u)
print("\nw:\n", w)
print("\n- np.insert(u, [1], w, axis=1)\n", np.insert(u, [1], w, axis=1))


u:
 [[ 6  2]
 [ 8  8]
 [11  7]]

w:
 [[ 2 10 12]
 [15 11  1]
 [14  6  3]]

- np.insert(u, [1], w, axis=1)
 [[ 6  2 10 12  2]
 [ 8 15 11  1  8]
 [11 14  6  3  7]]


- append() pour ajouter des valeurs constantes à la fin du tableau ne marche

In [88]:
a = np.random.randint(1, 16, (3, 5))
# a = (np.arange(1, 16)).reshape(3, 5)
# a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("a:\n", a)
b = np.ones(5).reshape(1, 5)
print("\n- np.append(a, np.ones(5), axis=0)\n", np.append(a,b, axis=0))

a:
 [[14  4 12  6  2]
 [10  7 12 13  6]
 [11  4  8  3  7]]

- np.append(a, np.ones(5), axis=0)
 [[14.  4. 12.  6.  2.]
 [10.  7. 12. 13.  6.]
 [11.  4.  8.  3.  7.]
 [ 1.  1.  1.  1.  1.]]


In [ ]:
a = (np.arange(1, 16)).reshape(3, 5)
print("a:\n", a)
print("\n- np.append(a, np.zeros(3, 2), axis=1)\n", np.append(a, np.zeros(3, 2), axis=1))

In [ ]:
a = (np.arange(1, 16)).reshape(3, 5)
print("a:\n", a)

print("\n- np.pad(a, ((0, 0), (0, 2))):\n", np.pad(a, ((0, 0), (0, 2))))

In [ ]:
a = (np.arange(1, 16)).reshape(3, 5)
print("a:\n", a)

print("\n- np.pad(a, (1)):\n", np.pad(a, 1))

In [ ]:
a = (np.arange(1, 16)).reshape(3, 5)
print("a:\n", a)

print("\n- np.pad(a, ((0, 1), (0, 0)), constant_values=1):\n", np.pad(a, ((0, 1), (0, 0)), constant_values=1))

### Meshgrid : Le maillaige

- The C way

In [ ]:
a = np.empty((2, 3))
for i in range(2):
    for j in range(3):
        a[i, j] = j-i
print(a)

- The Python way

In [ ]:
c= [[(j-i) for j in range(3)] for i in range(2)]
a= np.array(c)
print(a)

- The Matlab way

In [ ]:
i, j = np.arange(2), np.arange(3)
print("- i:\n", i)
print("\n- j:\n", j)

I, J = np.meshgrid(i, j, indexing='ij')
print("- I:\n", I)
print("\n- J:\n", J)

- The Numpy way

In [ ]:
i, j = np.arange(2), np.arange(3)
print("- i:\n", i)
print("\n- j:\n", j)

I, J = np.meshgrid(i, j, sparse=True, indexing='ij')
print("- I:\n", I)
print("\n- J:\n", J)

print("\n- J-I:\n", J-I)


In [ ]:
a = (np.arange(1, 5)).reshape(2, 2)
I, J = np.indices(a.shape)
print("- I:\n", I)
print("\n- J:\n", J)

print("\na[I, J]:\n", a[I, J])
print("\na[J, I]:\n", a[J, I])

#### - Les Statiques des matrices

Parmis ces statistiques figurent les methodes sum, min, max, argmin, argmax, mean, median, percentile, std, var...

In [ ]:
a = np.array([[4, 8, 5], [9, 3, 1]])
print("- a.min()\n", a.min())
print("\n- a.min(axis=0)\n", a.min(axis=0))
print("\n- a.min(axis=1)\n", a.min(axis=1))

In [ ]:
# argmin retourne l'indice du plus petit element du tableau
print("- a.argmin()\n", a.argmin())
print("- a.argmin(axis=0)\n", a.argmin(axis=1))
print("- a.argmin(axis=1)\n", a.argmin(axis=1))

In [ ]:
# Les quantificateurs any et all utilisent aussi l'argument "axis"
print("- np.any(a>5)\n", np.any(a>5))
print("- np.any(a>5, axis=0)\n", np.any(a>5, axis=0))
print("- np.any(a>5, axis=1)\n", np.any(a>5, axis=1))

#### Trie dans une matrice

In [ ]:
a = np.array([[4, 8, 5], [9, 3, 1]])
print("a:\n", a)

print("\n- a.sort()\n", a.sort())
print("\n- np.sort(a)\n",np.sort(a))
print("\n- np.sort(a, axis=-1)\n", np.sort(a, axis=-1))
print("\n- np.sort(a, axis=1)\n", np.sort(a, axis=1))
print("\n- np.sort(a, axis=0)\n", np.sort(a, axis=0))

In [ ]:
a = (np.array([[7, 4, 6, 5]])).T
print("a:\n", a)
a_trie = np.sort(a, axis = 0)
print("\n- np.sort(a, axis = 0)\n", a_trie)
print("\n- np.argsort(a, axis = 0)\n", np.argsort(a, axis = 0))

In [ ]:
b = np.array([[3, 8], [0, 4], [1, 7], [2, 9]])
print("b:\n", b)
c = np.hstack((a_trie, b))
print("\n- c:\n", c)
print("\n- c[[1, 3, 2, 0]]\n", c[[1, 3, 2, 0]] )
print("\n- c[np.argsort(c[:,0])]\n", c[np.argsort(b[:,0])])

In [ ]:
a = np.array([[3, 4], [2, 7], [1, 5], [2, 6]])
x = a[a[:,0].argsort()]
print("- x:\n", x)
y = a[a[:,1].argsort(kind='stable')]
print("\n- y:\n", y)
z = a[a[:,0].argsort(kind='stable')]
print("\n- z:\n", z)
x1 = a[np.argsort(a[:,1])]
print("\n- x1:\n", x1)
x2 = a[np.argsort(x1[:,0], kind='stable')]
print("\n- x2:\n", x2)

In [ ]:
a = np.array([[3, 4], [2, 7], [1, 5], [2, 6]])
print("a[np.lexsort(np.rot90(a))]:\n", a[np.lexsort(np.rot90(a))])

In [ ]:
a = np.array([[3, 4], [2, 7], [1, 5], [2, 6]])
print("a[np.lexsort(np.flipud(a.T[[2,5]]))]:\n", a[np.lexsort(np.flipud(a.T[[0,1]]))])

In [ ]:
a = np.array([[3, 4], [2, 7], [1, 5], [2, 6]])
from numpy.lib.recfunctions import unstructured_to_structured as u2s
from numpy.lib.recfunctions import structured_to_unstructured as s2u
b = u2s(a)
print("- u2s(a)\n", b)
b = np.sort(b, axis=0)
print("\n- b.sort(order=('f1', 'f0')):\n", b)
print("- s2u(a)\n", s2u(b))

# 3D

In [ ]:
np.arange(1, 9).reshape(2, 2, 2)

In [48]:
b = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1], [2, 2, 2, 2], [2, 2, 2, 2]]).reshape(3, 2, 4)
print("ndim:", b.ndim)
print("\nsize:", b.size)

ndim: 3

size: 24


In [57]:
b = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1], [2, 2, 2, 2], [2, 2, 2, 2]])
b = np.dstack(b)
b

array([[[0, 0, 1, 1, 2, 2],
        [0, 0, 1, 1, 2, 2],
        [0, 0, 1, 1, 2, 2],
        [0, 0, 1, 1, 2, 2]]])

In [61]:
print("- zeros:\n", np.zeros((3, 4, 5)))
print("\- nones:\n", np.ones((3, 4, 5)))
print("\n- Random:\n", np.random.rand(3, 4, 5))

- zeros:
 [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
\- nones:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

- Random:
 [[[0.8756903  0.24685114 0.63898891 0.11067709 0.88729494]
  [0.54038592 0.30271986 0.24159409 0.53885214 0.17248042]
  [0.74532254 0.60628313 0.96927274 0.60938553 0.80371141]
  [0.45995386 0.12953982 0.36641517 0.50534006 0.70341153]]

 [[0.42823318 0.5216468  0.53765387 0.54112449 0.66925734]
  [0.6486889  0.44880571 0.30350491 0.32870119 0.57368528]
  [0.49967262 0.93062368 0.20531572 0.4748163  0.1694381 ]
  [0.07927166 0.41845533 0.32714313 0.20032547 0.91611262]]

 [[0.112129   0.7579103

In [65]:
a = np.random.randint(1, 16, (3, 4))
b = np.random.randint(1, 7, (3, 2))
c = np.random.randint(1, 9, (2, 4))
d = np.random.randint(1, 9, (3, 4))
print("- np.hstack", np.hstack((a, b)))
print("\n- np.vstack",np.vstack((a, c)))
print("\n- np.dstack",np.dstack((a, d)))

- np.hstack [[ 4 11  5  4  1  5]
 [11 10  5  9  4  6]
 [ 5  2 15  4  2  5]]

- np.vstack [[ 4 11  5  4]
 [11 10  5  9]
 [ 5  2 15  4]
 [ 3  1  4  8]
 [ 2  4  8  2]]

- np.dstack [[[ 4  3]
  [11  4]
  [ 5  1]
  [ 4  5]]

 [[11  8]
  [10  8]
  [ 5  7]
  [ 9  2]]

 [[ 5  7]
  [ 2  8]
  [15  2]
  [ 4  3]]]


In [67]:
#concatenation
a = np.random.randint(1, 16, (2, 3,  4))
b = np.random.randint(1, 7, (2, 3, 2))
c = np.random.randint(1, 9, (2, 2, 4))
d = np.random.randint(1, 9, (2, 3, 4))
print("- concatenate suivant x:\n", np.concatenate((a, b), axis=2))
print("\n- concatenate suivant y:\n",np.concatenate((a, c), axis=1))
print("\n- concatenate suivant z:\n",np.concatenate((a, d), axis=0))

- concatenate suivant x:
 [[[11 13 13 10  1  1]
  [12 14  4 13  4  3]
  [15  6  3  1  5  6]]

 [[ 1  7  3  8  4  5]
  [14  7  6  5  1  4]
  [ 2  8 11  5  4  4]]]

- concatenate suivant y:
 [[[11 13 13 10]
  [12 14  4 13]
  [15  6  3  1]
  [ 8  7  6  8]
  [ 3  8  8  1]]

 [[ 1  7  3  8]
  [14  7  6  5]
  [ 2  8 11  5]
  [ 1  6  2  3]
  [ 5  6  6  7]]]

- concatenate suivant z:
 [[[11 13 13 10]
  [12 14  4 13]
  [15  6  3  1]]

 [[ 1  7  3  8]
  [14  7  6  5]
  [ 2  8 11  5]]

 [[ 7  6  1  8]
  [ 1  8  6  2]
  [ 4  8  3  7]]

 [[ 6  2  6  2]
  [ 7  3  7  3]
  [ 5  7  8  4]]]


In [74]:
b = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1], [1, 1, 1, 1], [2, 2, 2, 2], [2, 2, 2, 2]])
b = b.reshape(3, 2, 4)
print("- b initial:\n", b)
c = np.moveaxis(b, 0, 2)
print("\n- c:\n", c)
b = np.moveaxis(c, 0, 2)
print("\n- b:\n", b)

- b initial:
 [[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]]]

- c:
 [[[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]

- b:
 [[[0 0]
  [1 1]
  [2 2]]

 [[0 0]
  [1 1]
  [2 2]]

 [[0 0]
  [1 1]
  [2 2]]

 [[0 0]
  [1 1]
  [2 2]]]


In [79]:
a = np.random.randint(1, 13, (2, 4,  3))
x = np.swapaxes(a, 1, 2)
y = np.swapaxes(a, 0, 1)
z = np.swapaxes(a, 1, 2)
print("- np.swapaxes(a, 1, 2):\n", x)
print("\n- np.swapaxes(a, 0, 1):\n", y)
print("\n- np.swapaxes(a, 0, 2):\n", z)
print("\n-x.shape :", x.shape)
print("\n-y.shape :", y.shape)
print("\n-z.shape :", z.shape)

- np.swapaxes(a, 1, 2):
 [[[ 5  5  3 12]
  [ 1  7  4  8]
  [ 5 11 11 11]]

 [[ 7 11  2  7]
  [11  7 10  9]
  [10  3 10  9]]]

- np.swapaxes(a, 0, 1):
 [[[ 5  1  5]
  [ 7 11 10]]

 [[ 5  7 11]
  [11  7  3]]

 [[ 3  4 11]
  [ 2 10 10]]

 [[12  8 11]
  [ 7  9  9]]]

- np.swapaxes(a, 0, 2):
 [[[ 5  5  3 12]
  [ 1  7  4  8]
  [ 5 11 11 11]]

 [[ 7 11  2  7]
  [11  7 10  9]
  [10  3 10  9]]]

-x.shape : (2, 3, 4)

-y.shape : (4, 2, 3)

-z.shape : (2, 3, 4)


In [81]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
np.einsum('ijk,jil->kl', a, b)

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])